language: php

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script: composer test

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

matrix:
  include:
    - php: 5.6
      env: ILLUMINATE_VERSION=5.1.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.5.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.*
